---
layout: cv
title: Isaac Newtons's CV
editor: 
  markdown: 
    wrap: 72
---

# CAMILA RAMIREZ SUAREZ

385 457 9947 \| camilaramirezsuarez2086\@gmail.com \|
www.linkedin.com/in/camila ramirez suarez

## EDUCATION Bachelor of Science September

2022 - December 2026 Brigham Young University - Idaho

• BYU-Idaho Scholarship 2023-2025

• Member, Data Science Society

## EXPERIENCE

### Data Analyst - Institutional Data & Analysis Services October 2025

• Utilizing SQL, Excel, and Power BI to create dashboards and visual
summaries of key performance indicators

• Extracting, cleaning, and analyzing large institutional datasets using
SQL and Excel to support decision-making across multiple departments

• Appling statistical methods to identify patterns and insights in large
student and operational datasets. • Collaborating with a
cross-functional team of analysts, IT developers, and institutional
leaders to standardize data definitions across 10+ departments,
enhancing reporting accuracy and consistency

### Teaching Assistant - Data Science Department April 2025 -

• Designed ITM 295 course structure with 12 modules and rubrics,
restructuring curriculum delivery for 100+ students/semester

• Developed course website, increasing accessibility and reducing
student navigation issues by 30%

• Centralized resources and automated workflows, cutting faculty prep
time by 20%

### Research Assistant - Cancer Genomics Statistical Analysis January -

• Analyzed 500+ genomic datasets in R, identifying significant
correlations to guide research outcomes • Produced 15+ visualizations
and reports used in a peer-reviewed academic manuscript

• Coordinated with 4 researchers to align deliverables with project
deadlines

### Independent Researcher - International Baccalaureate 2020-2022

• Led 2-year biology research project, securing \$7,000 in competitive
funding

• Managed 200+ trials with full data collection, analysis, and
interpretation

• Presented findings to 10+ evaluators, earning top scores and Summa Cum
Laude distinction

## PROJECTS

Applied Data Science & Visualization Projects\
• Cleaned, transformed, and analyzed real-world datasets using R to
answer open-ended analytical questions

• Designed data visualizations emphasizing clarity, storytelling, and
decision-making for non-technical audiences

• Developed portfolio-style dashboards and reports summarizing key
insights and trends
